name: Terraform Output

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: azureuser
          port: 22
          key: ${{ secrets.VM_KEY }}
          source: "weather.py"
          target: "/home/azureuser"
